### ISSUE TITLE
Add a check for the sidekiq process pid

### ISSUE THREAD

**Issue by fabioperrella** [locaweb/heartcheck-sidekiq#9]
There is no error when the Sidekiq process is dead.

I implemented a process monitoring in my app like this:
```ruby
monitor.add :process do |config|
  config.name = 'sidekiq-process'
  config.add_service(
    name: 'sidekiq',
    file: File.join(Rails.root, 'tmp', 'pids', 'sidekiq.pid')
  )
end
```

But I think this check could be implemented here in this gem

**Comment by gleopoldo** [comment]
Hello!

I've made some tests with this issue, but hadn't yet enough time to reach a PR for this... I'm thinking on refactoring that check to expose two types of validations (one for redis connectivity, other for process lookup) into two different classes that are able to append errors to the main check (this is the most difficult part, since the check is very coupled with the error appending logic).

The other option is to provide a new check, something like sidekiq-process (since heartcheck will use a `constantize` to evaluate it into a class), but, although simpler, I'm not sure if this is a good approach from a usage perspective. Any ideas? WDYT?
